.\"
.\"     %A%
.\"
.Dd March 31, 2004
.Dt RUNQ 1
.Os MASTODON
.Sh NAME
.Nm runq
.Nd run the mail queue
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl o Ns Ar relay-host= Ns Nm host
.Sh DESCRIPTION
.Nm
processes saved messages in the mail queue.
.Pp
.Nm
is identical to
.Dq Li "postoffice -bq" .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl v
Print verbose information.
This makes
.Nm
display the
conversation with each remote 
server it sends mail to.
.It Fl o Ns Ar relay-host= Ns Nm host
Relay all mail through
.Sy host
instead of trying to send directly to remote machines.  
.Sy root
is the only account that may use this option.
.El
.Pp
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
.Xr postoffice 8
.Sh HISTORY
The
.Nm
command is from
.Bx .
